USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE DBT_WAREHOUSE WITH WAREHOUSE_SIZE = 'X-SMALL';
CREATE DATABASE DBT_DATABASE;
CREATE ROLE DBT_ROLE;

GRANT USAGE ON WAREHOUSE DBT_WAREHOUSE TO ROLE DBT_ROLE;
GRANT ROLE DBT_ROLE TO USER YOUR_SNOWFLAKE_USERNAME;
GRANT ALL ON DATABASE DBT_DATABASE TO ROLE DBT_ROLE;

USE ROLE DBT_ROLE;

CREATE SCHEMA DBT_DATABASE.DBT_SCHEMA;

